#ifndef PARAMETERS_H
#define PARAMETERS_H

#define MAX_VOICES 8

#define SAMPLE_PARAMETER_OFFSET ((PARAM_COUNT * MAX_VOICES)  + 1) // () are VERY important
#define APPLY_PARAM_OFFSET(voice, param, paramCount) (param + (voice * paramCount))
#define REMOVE_PARAM_OFFSET(param_index_with_offset,paramCount) ((param_index_with_offset) % paramCount)
#define PARAM_VOICE_NUMBER(param_index_with_offset,paramCount) ((param_index_with_offset) / paramCount)


typedef enum {
    PARAM_AMP,
    PARAM_FREQ,
    PARAM_OSC_PHASE,
    PARAM_LFO_PHASE,
    PARAM_GATE,
    PARAM_VEL,
    PARAM_AMP_LEVEL,
    PARAM_AMP_2_LEVEL,
    PARAM_AMP_ENV_ATTACK,
    PARAM_AMP_ENV_DECAY,
    PARAM_AMP_ENV_SUSTAIN,
    PARAM_AMP_ENV_RELEASE,
    PARAM_AMP_ENV_DEPTH,
    PARAM_FILTER_ENV_DEPTH,
    PARAM_FILTER_ENV_ATTACK,
    PARAM_FILTER_ENV_DECAY,
    PARAM_FILTER_ENV_SUSTAIN,
    PARAM_FILTER_ENV_RELEASE,
    PARAM_PITCH_ENV_DEPTH,
    PARAM_PITCH_ENV_ATTACK,
    PARAM_PITCH_ENV_DECAY,
    PARAM_PITCH_ENV_SUSTAIN,
    PARAM_PITCH_ENV_RELEASE,
    PARAM_CUTOFF,
    PARAM_RES,
    PARAM_TUNE,
    PARAM_OSC_TYPE,
    PARAM_OSC_2_TYPE,
    PARAM_FILTER_TYPE,
    PARAM_AMP_LFO_DEPTH,
    PARAM_AMP_LFO_SPEED,
    PARAM_FILTER_LFO_DEPTH,
    PARAM_FILTER_LFO_SPEED,
    PARAM_PITCH_LFO_DEPTH,
    PARAM_PITCH_LFO_SPEED,
    PARAM_OSC_BASE_FREQ,
    PARAM_FILTER_BASE_CUTOFF,
    PARAM_PHASE_RESET,
    PARAM_RETRIGGER,
    SAMPLE_LOAD,
    SAMPLE_RECORD_START,
    SAMPLE_RECORD_STOP,
    PARAM_MORPH_AMOUNT,
    PARAM_BASE_MORPH_AMOUNT,
    PARAM_MORPH_LFO_DEPTH,
    PARAM_MORPH_LFO_SPEED,
    PARAM_PLAYBACK_RATE,
    PARAM_IFX,
    PARAM_UNISON,
    PARAM_ASSIGN_SAMPLE_TO_VOICE,

    PARAM_COUNT
} e_param;

typedef enum  {
    SAMPLE_SELECTED_SAMPLE,
    SAMPLE_RECORDING_THRESHOLD,
    SAMPLE_RECORDING_TIME_IN_MS,
    SAMPLE_GLOBAL_OFFSET,
    SAMPLE_PLAYBACK_RATE,
    SAMPLE_START_POINT,
    SAMPLE_LENGTH,
    SAMPLE_LOOP_POINT,
    SAMPLE_PARAM_QUALITY,
    SAMPLE_PARAM_ROOT_NOTE,
    SAMPLE_PARAM_HI_NOTE,
    SAMPLE_PARAM_LOW_NOTE,
    SAMPLE_PARAM_COUNT

} e_sample_param;

#endif